// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// // import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC3mazZxFxHYMxef1KBtaJvIDdty9cFzqE',
//     appId: '1:165258193888:web:8b07df617e4e6310385985',
//     messagingSenderId: '165258193888',
//     projectId: 'smart-shop-2026-59d5f',
//     authDomain: 'smart-shop-2026-59d5f.firebaseapp.com',
//     storageBucket: 'smart-shop-2026-59d5f.firebasestorage.app',
//     measurementId: 'G-LRC6HJST8K',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCpuBoZdt6K7AEEGsWdqh506rk5ZPYvp_M',
//     appId: '1:165258193888:android:260e971017a0232b385985',
//     messagingSenderId: '165258193888',
//     projectId: 'smart-shop-2026-59d5f',
//     storageBucket: 'smart-shop-2026-59d5f.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDHrPB3unWVe864QKqBYs_00i04Q7tilds',
//     appId: '1:165258193888:ios:ac07f7e2dec97939385985',
//     messagingSenderId: '165258193888',
//     projectId: 'smart-shop-2026-59d5f',
//     storageBucket: 'smart-shop-2026-59d5f.firebasestorage.app',
//     iosBundleId: 'com.example.myapp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDHrPB3unWVe864QKqBYs_00i04Q7tilds',
//     appId: '1:165258193888:ios:ac07f7e2dec97939385985',
//     messagingSenderId: '165258193888',
//     projectId: 'smart-shop-2026-59d5f',
//     storageBucket: 'smart-shop-2026-59d5f.firebasestorage.app',
//     iosBundleId: 'com.example.myapp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyC3mazZxFxHYMxef1KBtaJvIDdty9cFzqE',
//     appId: '1:165258193888:web:2fb3c8fa1c80ba96385985',
//     messagingSenderId: '165258193888',
//     projectId: 'smart-shop-2026-59d5f',
//     authDomain: 'smart-shop-2026-59d5f.firebaseapp.com',
//     storageBucket: 'smart-shop-2026-59d5f.firebasestorage.app',
//     measurementId: 'G-2PW5SZYBTY',
//   );
// }
